SPI.APARTAMENTO_VISTORIA_HISTORICO=\
INSERT INTO apartamento_vistoria_historico ( \
    id_apartamento_vistoria, \
    nr_versao, \
    nm_atributo, \
    tx_anterior, \
    tx_atual \
) \
VALUES ( \
    :idApartamentoVistoria, \
    :nrVersao, \
    :nmAtributo, \
    :txAnterior, \
    :txAtual \
)

SPS.APARTAMENTO_VISTORIA_HISTORICO=\
SELECT \
    nr_versao AS nrVersao, \
    nm_atributo AS nmAtributo, \
    tx_anterior AS txAnterior, \
    tx_atual AS txAtual, \
    dt_alteracao AS dtAlteracao, \
    nm_usuario AS nmUsuario \
FROM apartamento_vistoria_historico \
WHERE id_apartamento_vistoria = :idApartamentoVistoria \
ORDER BY nr_versao ASC, id_apartamento_vistoria_historico ASC

SPS.APARTAMENTO_VISTORIA_HISTORICO_NR_VERSAO=\
SELECT \
    nr_versao AS nrVersao \
FROM apartamento_vistoria_historico \
WHERE id_apartamento_vistoria = :idApartamentoVistoria